server:
  port: 80

spring:

  thymeleaf:
    mode: HTML

  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

# 用于通过IP查找地址的百度API
baiduApi:
  accessKey: 0962af51ad37430786a8723d9e018f71
  secretKey: f3c38615a64c4a6cbdc48fe2717830bc

# 用于微信推送消息
pushMessage:
  token: 
